[package]
name = "cobrac"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The Cobra programming language command-line compiler and interpreter"

[[bin]]
name = "cobrac"
path = "src/main.rs"

[dependencies]
cobra-diagnostics-telemetry.workspace = true
cobra-lexer-quantum.workspace = true
cobra-parser-ast.workspace = true
cobra-runtime-core.workspace = true